services:
  - type: web
    name: pharmacie-221
    runtime: node
    repo: https://github.com/MalickDevWeb/GestPharmacieApi_express_221.git
    branch: prod
    plan: free
    region: oregon
    autoDeployTrigger: checksPass
    buildCommand: npm ci --include=dev && npm run prisma:generate && npm run build
    startCommand: npm run prisma:migrate:deploy && npm run start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: info
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pharmacie-221-db
          property: connectionString

databases:
  - name: pharmacie-221-db
    databaseName: pharma_221
    user: pharma_221_user
    plan: free
    region: oregon
    postgresMajorVersion: "18"
